(function () {
  // Har bir mahsulot alohida obyekt.
  // Quyidan p1, p2 ... p50 ni qolda tahrirlashingiz mumkin.
  var products = [];

  function metaFromPairs(pairs) {
    var meta = {};
    for (var i = 0; i < pairs.length; i++) {
      var idx = i + 1;
      meta["k" + idx] = pairs[i][0];
      meta["v" + idx] = pairs[i][1];
    }
    return meta;
  }

  function addProduct(id, sku, price, images, uz, ru, en) {
    products.push({
      id: id,
      sku: sku,
      price_uzs: price,
      images: (Array.isArray(images) && images.length ? images : ["./images/" + id + ".png"]),
      uz: uz,
      ru: ru,
      en: en,
    });
  }

  addProduct(
    "p1",
    "RM-001",
    0,
    ["./images/totrburchak-kontey.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "To'rtburchak konteyner (qopqoqli)",
      desc: "To'rtburchak, qopqoqli konteyner. Ikki sig'im varianti: 1000 ml va 800 ml.",
      meta: metaFromPairs([
        ["Turi", "To'rtburchak, qopqoqli"],
        ["Uzunlik (mm)", "175 / 175"],
        ["Balandlik (mm)", "58 / 50"],
        ["Kenglik (mm)", "130 / 130"],
        ["Sig'im", "1000 ml / 800 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер прямоугольный с крышкой",
      desc: "Прямоугольный контейнер с крышкой. Два объёма: 1000 мл и 800 мл.",
      meta: metaFromPairs([
        ["Тип", "Прямоугольный, с крышкой"],
        ["Длина (мм)", "175 / 175"],
        ["Высота (мм)", "58 / 50"],
        ["Ширина (мм)", "130 / 130"],
        ["Объём", "1000 мл / 800 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Rectangular container with lid",
      desc: "Rectangular container with lid. Two volumes: 1000 ml and 800 ml.",
      meta: metaFromPairs([
        ["Type", "Rectangular, with lid"],
        ["Length (mm)", "175 / 175"],
        ["Height (mm)", "58 / 50"],
        ["Width (mm)", "130 / 130"],
        ["Volume", "1000 ml / 800 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );

  addProduct(
    "p2",
    "RM-002",
    0,
    ["./images/supnitsa.png"],
    {
      title: "Mahsulot",
      category: "Termo",
      badge: "Termo",
      name: "Supnitsa + qopqoq",
      desc: "Supnitsa va qopqoq komplekti.",
      meta: metaFromPairs([
        ["Turi", "Supnitsa, qopqoqli"],
        ["Uzunlik (mm)", "133"],
        ["Balandlik (mm)", "70"],
        ["Kenglik (mm)", "135"],
        ["Sig'im", "550 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Термо",
      badge: "Термо",
      name: "Супница + крышка",
      desc: "Формат «супница + крышка».",
      meta: metaFromPairs([
        ["Тип", "Супница, с крышкой"],
        ["Длина (мм)", "133"],
        ["Высота (мм)", "70"],
        ["Ширина (мм)", "135"],
        ["Объём", "550 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Thermo",
      badge: "Thermo",
      name: "Soup cup + lid",
      desc: "Soup cup with lid.",
      meta: metaFromPairs([
        ["Type", "Soup cup, with lid"],
        ["Length (mm)", "133"],
        ["Height (mm)", "70"],
        ["Width (mm)", "135"],
        ["Volume", "550 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );

  addProduct(
    "p3",
    "RM-003",
    1650,
    ["./images/stakan gl.png"],
    {
      title: "Mahsulot",
      category: "Stakan",
      badge: "Stakan",
      name: "Silliq stakan + qopqoq",
      desc: "Silliq stakan va qopqoq komplekti.",
      meta: metaFromPairs([
        ["Turi", "Silliq stakan, qopqoqli"],
        ["Balandlik (mm)", "135 / 173"],
        ["Diametr (mm)", "89 / 89"],
        ["Sig'im", "500 ml / 700 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Стакан",
      badge: "Стакан",
      name: "Стакан гладкий + крышка",
      desc: "Комплект стакан + крышка.",
      meta: metaFromPairs([
        ["Тип", "Гладкий стакан, с крышкой"],
        ["Высота (мм)", "135 / 173"],
        ["Диаметр (мм)", "89 / 89"],
        ["Объём", "500 мл / 700 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Cup",
      badge: "Cup",
      name: "Smooth cup + lid",
      desc: "Smooth cup with lid set.",
      meta: metaFromPairs([
        ["Type", "Smooth cup, with lid"],
        ["Height (mm)", "135 / 173"],
        ["Diameter (mm)", "89 / 89"],
        ["Volume", "500 ml / 700 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );

  addProduct(
    "p4",
    "RM-004",
    1650,
    ["./images/stakan-qopqoq-n1.png"],
    {
      title: "Mahsulot",
      category: "Qopqoq",
      badge: "Qopqoq",
      name: "Stakan uchun qopqoq",
      desc: "Stakan uchun qopqoq.",
      meta: metaFromPairs([
        ["Turi", "Stakan uchun qopqoq"],
        ["Uzunlik (mm)", "91"],
        ["Balandlik (mm)", "25"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Крышка",
      badge: "Крышка",
      name: "Крышка для стакана",
      desc: "Крышка для стакана.",
      meta: metaFromPairs([
        ["Тип", "Крышка для стакана"],
        ["Длина (мм)", "91"],
        ["Высота (мм)", "25"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Lid",
      badge: "Lid",
      name: "Cup lid",
      desc: "Cup lid.",
      meta: metaFromPairs([
        ["Type", "Cup lid"],
        ["Length (mm)", "91"],
        ["Height (mm)", "25"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );

  addProduct(
    "p5",
    "RM-005",
    1750,
    ["./images/stakan-qopqoq-n2.png"],
    {
      title: "Mahsulot",
      category: "Qopqoq",
      badge: "Qopqoq",
      name: "Stakan uchun qopqoq",
      desc: "Stakan uchun qopqoq.",
      meta: metaFromPairs([
        ["Turi", "Stakan uchun qopqoq"],
        ["Uzunlik (mm)", "91"],
        ["Balandlik (mm)", "45"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Крышка",
      badge: "Крышка",
      name: "Крышка для стакана",
      desc: "Крышка для стакана.",
      meta: metaFromPairs([
        ["Тип", "Крышка для стакана"],
        ["Длина (мм)", "91"],
        ["Высота (мм)", "45"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Lid",
      badge: "Lid",
      name: "Cup lid",
      desc: "Cup lid.",
      meta: metaFromPairs([
        ["Type", "Cup lid"],
        ["Length (mm)", "91"],
        ["Height (mm)", "45"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );

      addProduct(
    "p6",
    "RM-006",
    2370,
    ["./images/chele-85.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "85"],
        ["Kenglik (mm)", "316"],
        ["Sig'im", "550 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "85"],
        ["Ширина (мм)", "316"],
        ["Объём", "550 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "85"],
        ["Width (mm)", "316"],
        ["Volume", "550 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p7",
    "RM-007",
    2465,
    ["./images/chele-78.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "78"],
        ["Kenglik (mm)", "320"],
        ["Sig'im", "550 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "78"],
        ["Ширина (мм)", "320"],
        ["Объём", "550 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "78"],
        ["Width (mm)", "320"],
        ["Volume", "550 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p8",
    "RM-008",
    2560,
    ["./images/chele-70.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Uzunlik (mm)", "70"],
        ["Balandlik (mm)", "115"],
        ["Kenglik (mm)", "115"],
        ["Sig'im", "350 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Длина (мм)", "70"],
        ["Высота (мм)", "115"],
        ["Ширина (мм)", "115"],
        ["Объём", "350 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Length (mm)", "70"],
        ["Height (mm)", "115"],
        ["Width (mm)", "115"],
        ["Volume", "350 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p9",
    "RM-009",
    2655,
    ["./images/chele-100.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Uzunlik (mm)", "100"],
        ["Balandlik (mm)", "40"],
        ["Kenglik (mm)", "480"],
        ["Sig'im", "200 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Длина (мм)", "100"],
        ["Высота (мм)", "40"],
        ["Ширина (мм)", "480"],
        ["Объём", "200 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Length (mm)", "100"],
        ["Height (mm)", "40"],
        ["Width (mm)", "480"],
        ["Volume", "200 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p10",
    "RM-010",
    2750,
    ["./images/chele-125.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "125"],
        ["Kenglik (mm)", "510"],
        ["Sig'im", "1000 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "125"],
        ["Ширина (мм)", "510"],
        ["Объём", "1000 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "125"],
        ["Width (mm)", "510"],
        ["Volume", "1000 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p11",
    "RM-011",
    2845,
    ["./images/chele-120.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "120"],
        ["Kenglik (mm)", "145"],
        ["Sig'im", "1000 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "120"],
        ["Ширина (мм)", "145"],
        ["Объём", "1000 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "120"],
        ["Width (mm)", "145"],
        ["Volume", "1000 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p12",
    "RM-012",
    2940,
    ["./images/chele-94.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "94"],
        ["Kenglik (mm)", "90"],
        ["Sig'im", "800 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "94"],
        ["Ширина (мм)", "90"],
        ["Объём", "800 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "94"],
        ["Width (mm)", "90"],
        ["Volume", "800 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p13",
    "RM-013",
    3035,
    ["./images/chele-125n2.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "125"],
        ["Kenglik (mm)", "115"],
        ["Sig'im", "900 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "125"],
        ["Ширина (мм)", "115"],
        ["Объём", "900 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "125"],
        ["Width (mm)", "115"],
        ["Volume", "900 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p14",
    "RM-014",
    3130,
    ["./images/chele-80.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "80"],
        ["Kenglik (mm)", "267"],
        ["Sig'im", "350 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "80"],
        ["Ширина (мм)", "267"],
        ["Объём", "350 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "80"],
        ["Width (mm)", "267"],
        ["Volume", "350 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p15",
    "RM-015",
    3225,
    ["./images/chele-90.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "90"],
        ["Kenglik (mm)", "94"],
        ["Sig'im", "450 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "90"],
        ["Ширина (мм)", "94"],
        ["Объём", "450 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "90"],
        ["Width (mm)", "94"],
        ["Volume", "450 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
      addProduct(
    "p16",
    "RM-016",
    3320,
    ["./images/chele-62.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "62"],
        ["Kenglik (mm)", "272"],
        ["Sig'im", "280 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "62"],
        ["Ширина (мм)", "272"],
        ["Объём", "280 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "62"],
        ["Width (mm)", "272"],
        ["Volume", "280 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p17",
    "RM-016",
    3320,
    ["./images/chele-70n2.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "70"],
        ["Kenglik (mm)", "243"],
        ["Sig'im", "170 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "70"],
        ["Ширина (мм)", "243"],
        ["Объём", "170 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "70"],
        ["Width (mm)", "243"],
        ["Volume", "170 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p18",
    "RM-017",
    3415,
    ["./images/smetana-stakann1.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "115"],
        ["Kenglik (mm)", "100"],
        ["Sig'im", "500 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "115"],
        ["Ширина (мм)", "100"],
        ["Объём", "500 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "115"],
        ["Width (mm)", "100"],
        ["Volume", "500 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p19",
    "RM-018",
    3510,
    ["./images/smetana-stakann2.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "95"],
        ["Kenglik (mm)", "100"],
        ["Sig'im", "400 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "95"],
        ["Ширина (мм)", "100"],
        ["Объём", "400 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "95"],
        ["Width (mm)", "100"],
        ["Volume", "400 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p20",
    "RM-019",
    3605,
    ["./images/qaymon1.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "55"],
        ["Kenglik (mm)", "197"],
        ["Sig'im", "200 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "55"],
        ["Ширина (мм)", "197"],
        ["Объём", "200 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "55"],
        ["Width (mm)", "197"],
        ["Volume", "200 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p21",
    "RM-020",
    3700,
    ["./images/qaymon2.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "70"],
        ["Kenglik (mm)", "260"],
        ["Sig'im", "200 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "70"],
        ["Ширина (мм)", "260"],
        ["Объём", "200 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "70"],
        ["Width (mm)", "260"],
        ["Volume", "200 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p22",
    "RM-021",
    3795,
    ["./images/sous.png"],
    {
      title: "Mahsulot",
      category: "Sousnitsa",
      badge: "Sousnitsa",
      name: "Plastik sousnitsa",
      desc: "Plastik sousnitsa modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik sousnitsa"],
        ["Balandlik (mm)", "30"],
        ["Kenglik (mm)", "160"],
        ["Sig'im", "50 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Соусница",
      badge: "Соусница",
      name: "Соусница пластиковая",
      desc: "Модель пластиковой соусницы.",
      meta: metaFromPairs([
        ["Тип", "Пластиковая соусница"],
        ["Высота (мм)", "30"],
        ["Ширина (мм)", "160"],
        ["Объём", "50 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Sauce cup",
      badge: "Sauce cup",
      name: "Plastic sauce cup",
      desc: "Plastic sauce cup model.",
      meta: metaFromPairs([
        ["Type", "Plastic sauce cup"],
        ["Height (mm)", "30"],
        ["Width (mm)", "160"],
        ["Volume", "50 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p23",
    "RM-022",
    3890,
    ["./images/chele-105.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Uzunlik (mm)", "105"],
        ["Balandlik (mm)", "90"],
        ["Kenglik (mm)", "105"],
        ["Sig'im", "200 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Длина (мм)", "105"],
        ["Высота (мм)", "90"],
        ["Ширина (мм)", "105"],
        ["Объём", "200 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Length (mm)", "105"],
        ["Height (mm)", "90"],
        ["Width (mm)", "105"],
        ["Volume", "200 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p24",
    "RM-023",
    3985,
    ["./images/konteyner.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "To'rtburchak konteyner (qopqoqli)",
      desc: "To'rtburchak, qopqoqli konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "To'rtburchak, qopqoqli konteyner"],
        ["Balandlik (mm)", "68"],
        ["Kenglik (mm)", "140"],
        ["Sig'im", "500 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер прямоугольный с крышкой",
      desc: "Модель прямоугольного контейнера с крышкой.",
      meta: metaFromPairs([
        ["Тип", "Прямоугольный контейнер с крышкой"],
        ["Высота (мм)", "68"],
        ["Ширина (мм)", "140"],
        ["Объём", "500 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Rectangular container with lid",
      desc: "Rectangular container with lid model.",
      meta: metaFromPairs([
        ["Type", "Rectangular container with lid"],
        ["Height (mm)", "68"],
        ["Width (mm)", "140"],
        ["Volume", "500 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p25",
    "RM-024",
    4080,
    ["./images/chele-150.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "150"],
        ["Kenglik (mm)", "545"],
        ["Sig'im", "3 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "150"],
        ["Ширина (мм)", "545"],
        ["Объём", "3 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "150"],
        ["Width (mm)", "545"],
        ["Volume", "3 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p26",
    "RM-025",
    4175,
    ["./images/p25.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "4 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "4 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "4 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p27",
    "RM-026",
    4270,
    ["./images/p26.png"],
    {
      title: "Mahsulot",
      category: "Chelak",
      badge: "Chelak",
      name: "Plastik chelak",
      desc: "Plastik chelak modeli.",
      meta: metaFromPairs([
        ["Turi", "Plastik chelak"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "5 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ведро",
      badge: "Ведро",
      name: "Ведро пластиковое",
      desc: "Модель пластикового ведра.",
      meta: metaFromPairs([
        ["Тип", "Пластиковое ведро"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "5 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Bucket",
      badge: "Bucket",
      name: "Plastic bucket",
      desc: "Plastic bucket model.",
      meta: metaFromPairs([
        ["Type", "Plastic bucket"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "5 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p28",
    "RM-027",
    4365,
    ["./images/p27.png"],
    {
      title: "Mahsulot",
      category: "Gul qozoni",
      badge: "Gul qozoni",
      name: "Gullar uchun kashpo",
      desc: "Gullar uchun plastik kashpo modeli.",
      meta: metaFromPairs([
        ["Turi", "Gullar uchun kashpo"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "12 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Кашпо",
      badge: "Кашпо",
      name: "Кашпо для цветов",
      desc: "Модель пластикового кашпо для цветов.",
      meta: metaFromPairs([
        ["Тип", "Кашпо для цветов"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "12 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Planter",
      badge: "Planter",
      name: "Flower planter",
      desc: "Plastic flower planter model.",
      meta: metaFromPairs([
        ["Type", "Flower planter"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "12 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p29",
    "RM-028",
    4460,
    ["./images/p28.png"],
    {
      title: "Mahsulot",
      category: "Gul qozoni",
      badge: "Gul qozoni",
      name: "Gullar uchun kashpo",
      desc: "Gullar uchun plastik kashpo modeli.",
      meta: metaFromPairs([
        ["Turi", "Gullar uchun kashpo"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "8 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Кашпо",
      badge: "Кашпо",
      name: "Кашпо для цветов",
      desc: "Модель пластикового кашпо для цветов.",
      meta: metaFromPairs([
        ["Тип", "Кашпо для цветов"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "8 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Planter",
      badge: "Planter",
      name: "Flower planter",
      desc: "Plastic flower planter model.",
      meta: metaFromPairs([
        ["Type", "Flower planter"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "8 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p30",
    "RM-029",
    4555,
    ["./images/p29.png"],
    {
      title: "Mahsulot",
      category: "Gul qozoni",
      badge: "Gul qozoni",
      name: "Gullar uchun kashpo",
      desc: "Gullar uchun plastik kashpo modeli.",
      meta: metaFromPairs([
        ["Turi", "Gullar uchun kashpo"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "6 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Кашпо",
      badge: "Кашпо",
      name: "Кашпо для цветов",
      desc: "Модель пластикового кашпо для цветов.",
      meta: metaFromPairs([
        ["Тип", "Кашпо для цветов"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "6 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Planter",
      badge: "Planter",
      name: "Flower planter",
      desc: "Plastic flower planter model.",
      meta: metaFromPairs([
        ["Type", "Flower planter"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "6 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p31",
    "RM-030",
    4650,
    ["./images/p30.png"],
    {
      title: "Mahsulot",
      category: "Gul qozoni",
      badge: "Gul qozoni",
      name: "Gullar uchun kashpo",
      desc: "Gullar uchun plastik kashpo modeli.",
      meta: metaFromPairs([
        ["Turi", "Gullar uchun kashpo"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "4 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Кашпо",
      badge: "Кашпо",
      name: "Кашпо для цветов",
      desc: "Модель пластикового кашпо для цветов.",
      meta: metaFromPairs([
        ["Тип", "Кашпо для цветов"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "4 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Planter",
      badge: "Planter",
      name: "Flower planter",
      desc: "Plastic flower planter model.",
      meta: metaFromPairs([
        ["Type", "Flower planter"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "4 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p32",
    "RM-031",
    4745,
    ["./images/p31.png"],
    {
      title: "Mahsulot",
      category: "Togora",
      badge: "Togora",
      name: "Togora",
      desc: "Plastik togora modeli.",
      meta: metaFromPairs([
        ["Turi", "Togora"],
        ["Balandlik (mm)", "80"],
        ["Kenglik (mm)", "670 / 190"],
        ["Sig'im", "2.5 l"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Togora",
      badge: "Togora",
      name: "Togora",
      desc: "Модель пластиковой тогоры.",
      meta: metaFromPairs([
        ["Тип", "Togora"],
        ["Высота (мм)", "80"],
        ["Ширина (мм)", "670 / 190"],
        ["Объём", "2.5 л"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Togora",
      badge: "Togora",
      name: "Togora",
      desc: "Plastic togora model.",
      meta: metaFromPairs([
        ["Type", "Togora"],
        ["Height (mm)", "80"],
        ["Width (mm)", "670 / 190"],
        ["Volume", "2.5 l"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p33",
    "RM-032",
    4840,
    ["./images/p32.png"],
    {
      title: "Mahsulot",
      category: "Chomich",
      badge: "Chomich",
      name: "Chomich",
      desc: "Plastik chomich modeli.",
      meta: metaFromPairs([
        ["Turi", "Chomich"],
        ["Balandlik (mm)", "80"],
        ["Kenglik (mm)", "200"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Чомич",
      badge: "Чомич",
      name: "Чомич",
      desc: "Модель пластикового чомича.",
      meta: metaFromPairs([
        ["Тип", "Чомич"],
        ["Высота (мм)", "80"],
        ["Ширина (мм)", "200"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Scoop",
      badge: "Scoop",
      name: "Scoop",
      desc: "Plastic scoop model.",
      meta: metaFromPairs([
        ["Type", "Scoop"],
        ["Height (mm)", "80"],
        ["Width (mm)", "200"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p34",
    "RM-033",
    4935,
    ["./images/p33.png"],
    {
      title: "Mahsulot",
      category: "Muzqaymoq konteyneri",
      badge: "Muzqaymoq konteyneri",
      name: "Muzqaymoq uchun konteyner",
      desc: "Muzqaymoq uchun plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Muzqaymoq uchun konteyner"],
        ["Uzunlik (mm)", "!"],
        ["Balandlik (mm)", "!"],
        ["Kenglik (mm)", "!"],
        ["Sig'im", "! ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер для мороженого",
      desc: "Модель пластикового контейнера для мороженого.",
      meta: metaFromPairs([
        ["Тип", "Контейнер для мороженого"],
        ["Длина (мм)", "!"],
        ["Высота (мм)", "!"],
        ["Ширина (мм)", "!"],
        ["Объём", "! мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Ice cream container",
      badge: "Ice cream container",
      name: "Ice cream container",
      desc: "Plastic ice cream container model.",
      meta: metaFromPairs([
        ["Type", "Ice cream container"],
        ["Length (mm)", "!"],
        ["Height (mm)", "!"],
        ["Width (mm)", "!"],
        ["Volume", "! ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
    addProduct(
    "p35",
    "RM-034",
    5030,
    ["./images/p34.png"],
    {
      title: "Mahsulot",
      category: "Sovun idishi",
      badge: "Sovun idishi",
      name: "Sovun idishi",
      desc: "Plastik sovun idishi modeli.",
      meta: metaFromPairs([
        ["Turi", "Sovun idishi"],
        ["Uzunlik (mm)", "125"],
        ["Balandlik (mm)", "45"],
        ["Kenglik (mm)", "90"],
        ["Sig'im", "200 ml"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Мыльница",
      badge: "Мыльница",
      name: "Мыльница",
      desc: "Модель пластиковой мыльницы.",
      meta: metaFromPairs([
        ["Тип", "Мыльница"],
        ["Длина (мм)", "125"],
        ["Высота (мм)", "45"],
        ["Ширина (мм)", "90"],
        ["Объём", "200 мл"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Soap dish",
      badge: "Soap dish",
      name: "Soap dish",
      desc: "Plastic soap dish model.",
      meta: metaFromPairs([
        ["Type", "Soap dish"],
        ["Length (mm)", "125"],
        ["Height (mm)", "45"],
        ["Width (mm)", "90"],
        ["Volume", "200 ml"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p36",
    "RM-035",
    5125,
    ["./images/p35.png"],
    {
      title: "Mahsulot",
      category: "Qoshiq",
      badge: "Qoshiq",
      name: "Kichik qoshiq",
      desc: "Plastik kichik qoshiq modeli.",
      meta: metaFromPairs([
        ["Turi", "Kichik qoshiq"],
        ["Uzunlik (mm)", "39"],
        ["Balandlik (mm)", "35"],
        ["Kenglik (mm)", "31"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Ложка",
      badge: "Ложка",
      name: "Ложка маленькая",
      desc: "Модель маленькой пластиковой ложки.",
      meta: metaFromPairs([
        ["Тип", "Ложка маленькая"],
        ["Длина (мм)", "39"],
        ["Высота (мм)", "35"],
        ["Ширина (мм)", "31"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Spoon",
      badge: "Spoon",
      name: "Small spoon",
      desc: "Plastic small spoon model.",
      meta: metaFromPairs([
        ["Type", "Small spoon"],
        ["Length (mm)", "39"],
        ["Height (mm)", "35"],
        ["Width (mm)", "31"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p37",
    "RM-036",
    5220,
    ["./images/p36.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 36",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "136"],
        ["Balandlik (mm)", "46"],
        ["Kenglik (mm)", "116"],
        ["Sig'im", "560 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 36",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "136"],
        ["Высота (мм)", "46"],
        ["Ширина (мм)", "116"],
        ["Объём", "560 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 36",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "136"],
        ["Height (mm)", "46"],
        ["Width (mm)", "116"],
        ["Volume", "560 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p38",
    "RM-037",
    5315,
    ["./images/p37.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 37",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "137"],
        ["Balandlik (mm)", "47"],
        ["Kenglik (mm)", "117"],
        ["Sig'im", "570 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 37",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "137"],
        ["Высота (мм)", "47"],
        ["Ширина (мм)", "117"],
        ["Объём", "570 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 37",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "137"],
        ["Height (mm)", "47"],
        ["Width (mm)", "117"],
        ["Volume", "570 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p39",
    "RM-038",
    5410,
    ["./images/p38.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 38",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "138"],
        ["Balandlik (mm)", "48"],
        ["Kenglik (mm)", "118"],
        ["Sig'im", "580 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 38",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "138"],
        ["Высота (мм)", "48"],
        ["Ширина (мм)", "118"],
        ["Объём", "580 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 38",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "138"],
        ["Height (mm)", "48"],
        ["Width (mm)", "118"],
        ["Volume", "580 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p40",
    "RM-039",
    5505,
    ["./images/p39.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 39",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "139"],
        ["Balandlik (mm)", "49"],
        ["Kenglik (mm)", "119"],
        ["Sig'im", "590 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 39",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "139"],
        ["Высота (мм)", "49"],
        ["Ширина (мм)", "119"],
        ["Объём", "590 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 39",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "139"],
        ["Height (mm)", "49"],
        ["Width (mm)", "119"],
        ["Volume", "590 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p41",
    "RM-040",
    5600,
    ["./images/p40.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 40",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "140"],
        ["Balandlik (mm)", "50"],
        ["Kenglik (mm)", "80"],
        ["Sig'im", "600 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 40",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "140"],
        ["Высота (мм)", "50"],
        ["Ширина (мм)", "80"],
        ["Объём", "600 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 40",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "140"],
        ["Height (mm)", "50"],
        ["Width (mm)", "80"],
        ["Volume", "600 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p42",
    "RM-041",
    5695,
    ["./images/p41.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 41",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "141"],
        ["Balandlik (mm)", "51"],
        ["Kenglik (mm)", "81"],
        ["Sig'im", "610 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 41",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "141"],
        ["Высота (мм)", "51"],
        ["Ширина (мм)", "81"],
        ["Объём", "610 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 41",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "141"],
        ["Height (mm)", "51"],
        ["Width (mm)", "81"],
        ["Volume", "610 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p43",
    "RM-042",
    5790,
    ["./images/p42.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 42",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "142"],
        ["Balandlik (mm)", "52"],
        ["Kenglik (mm)", "82"],
        ["Sig'im", "620 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 42",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "142"],
        ["Высота (мм)", "52"],
        ["Ширина (мм)", "82"],
        ["Объём", "620 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 42",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "142"],
        ["Height (mm)", "52"],
        ["Width (mm)", "82"],
        ["Volume", "620 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p44",
    "RM-043",
    5885,
    ["./images/p43.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 43",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "143"],
        ["Balandlik (mm)", "53"],
        ["Kenglik (mm)", "83"],
        ["Sig'im", "630 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 43",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "143"],
        ["Высота (мм)", "53"],
        ["Ширина (мм)", "83"],
        ["Объём", "630 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 43",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "143"],
        ["Height (mm)", "53"],
        ["Width (mm)", "83"],
        ["Volume", "630 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p45",
    "RM-044",
    5980,
    ["./images/p44.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 44",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "144"],
        ["Balandlik (mm)", "54"],
        ["Kenglik (mm)", "84"],
        ["Sig'im", "640 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 44",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "144"],
        ["Высота (мм)", "54"],
        ["Ширина (мм)", "84"],
        ["Объём", "640 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 44",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "144"],
        ["Height (mm)", "54"],
        ["Width (mm)", "84"],
        ["Volume", "640 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p46",
    "RM-045",
    6075,
    ["./images/p45.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 45",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "145"],
        ["Balandlik (mm)", "55"],
        ["Kenglik (mm)", "85"],
        ["Sig'im", "650 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 45",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "145"],
        ["Высота (мм)", "55"],
        ["Ширина (мм)", "85"],
        ["Объём", "650 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 45",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "145"],
        ["Height (mm)", "55"],
        ["Width (mm)", "85"],
        ["Volume", "650 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p47",
    "RM-046",
    6170,
    ["./images/p46.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 46",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "146"],
        ["Balandlik (mm)", "56"],
        ["Kenglik (mm)", "86"],
        ["Sig'im", "660 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 46",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "146"],
        ["Высота (мм)", "56"],
        ["Ширина (мм)", "86"],
        ["Объём", "660 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 46",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "146"],
        ["Height (mm)", "56"],
        ["Width (mm)", "86"],
        ["Volume", "660 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p48",
    "RM-047",
    6265,
    ["./images/p47.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 47",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "147"],
        ["Balandlik (mm)", "57"],
        ["Kenglik (mm)", "87"],
        ["Sig'im", "670 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 47",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "147"],
        ["Высота (мм)", "57"],
        ["Ширина (мм)", "87"],
        ["Объём", "670 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 47",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "147"],
        ["Height (mm)", "57"],
        ["Width (mm)", "87"],
        ["Volume", "670 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p49",
    "RM-048",
    6360,
    ["./images/p48.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 48",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "148"],
        ["Balandlik (mm)", "58"],
        ["Kenglik (mm)", "88"],
        ["Sig'im", "680 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 48",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "148"],
        ["Высота (мм)", "58"],
        ["Ширина (мм)", "88"],
        ["Объём", "680 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 48",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "148"],
        ["Height (mm)", "58"],
        ["Width (mm)", "88"],
        ["Volume", "680 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  addProduct(
    "p50",
    "RM-049",
    6455,
    ["./images/p49.png"],
    {
      title: "Mahsulot",
      category: "Konteyner",
      badge: "Konteyner",
      name: "Konteyner model 49",
      desc: "Plastik konteyner modeli.",
      meta: metaFromPairs([
        ["Turi", "Konteyner"],
        ["Uzunlik (mm)", "149"],
        ["Balandlik (mm)", "59"],
        ["Kenglik (mm)", "89"],
        ["Sig'im", "690 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Boglanish",
      cta2: "Katalogga qaytish",
    },
    {
      title: "Продукт",
      category: "Контейнер",
      badge: "Контейнер",
      name: "Контейнер модель 49",
      desc: "Модель пластикового контейнера.",
      meta: metaFromPairs([
        ["Тип", "Контейнер"],
        ["Длина (мм)", "149"],
        ["Высота (мм)", "59"],
        ["Ширина (мм)", "89"],
        ["Объём", "690 мл"],
        ["Материал", "PP"],
      ]),
      cta1: "Связаться",
      cta2: "Назад в каталог",
    },
    {
      title: "Product",
      category: "Container",
      badge: "Container",
      name: "Container model 49",
      desc: "Plastic container model.",
      meta: metaFromPairs([
        ["Type", "Container"],
        ["Length (mm)", "149"],
        ["Height (mm)", "59"],
        ["Width (mm)", "89"],
        ["Volume", "690 ml"],
        ["Material", "PP"],
      ]),
      cta1: "Contact",
      cta2: "Back to catalog",
    }
  );
  window.REALMAX_PRODUCTS = products;
})();




































